# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95cb5c42b615042d9bf21c2d46964c821454e0bad5393a5478bcf228b7b36a439576fdae7d1d86bf2b0f14dda1be49d234bead665d92a55487ff538523b11274

test:
  secret_key_base: 50765a0eac50242ae70dc18d022f7a49e4c20cfa24bbfff4692495dedff826af875c0e3b5759b0541c123c8873ebedbb50915a5dd49f3b8bcb7d8eaff2cdf6cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
